### ISSUE TITLE
Download Error: <item> is not listed in registration subscription for download

### ISSUE THREAD

**Issue by Xergy** [Azure/missionlz-edge#125]
When I run the download command after building the container images... I get several errors:

WARNING: Product : microsoft.customscriptextension-arm-1.10.13 is not listed in registration subscription for download.
WARNING: Product : microsoft.dsc-arm-2.83.1.0 is not listed in registration subscription for download.
Write-Error: Missing f5-networks.f5-big-ip-bestf5-bigip-virtual-edition-best-byol-15.1.004000 is a deal breaker since it is required for the landing zone.

Any Thoughts on why these are missing?

Note:  I moved the F5 to the bottom of the list, because I wasn't sure if there was an auth issue.

[Errors.txt](https://github.com/Azure/missionlz-edge/files/8683226/Errors.txt)

**Comment by shawngib** [comment]
This line will need to be changed to a version of F5 available in the subscription where the registration exist. 

https://github.com/Azure/missionlz-edge/blob/1a77f73c922a5736cc2f9f35194ccff30a0a75be/src/artifacts/defaultMlzMarketPlaceItems.txt#L1 

The reason this happens is a slight version drift of available versions between clouds/subscription where the registration lives. You can follow the instructions [here ](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-download-azure-marketplace-item?view=azs-2108&tabs=az1%2Caz2&pivots=state-disconnected#use-the-marketplace-syndication-tool-to-download-marketplace-items)to view the listing of available versions in that subscription. _Note, a modified version of the Syndication tool this link requires you to use is what is used inside the container. Do not replace the one in the container which comes from the ZIP file in the repos artifacts directory._

You should also change the available versions of _microsoft.customscriptextension_ and _microsoft.dsc-arm_ since those will be used in custom scripts which copy F5 configuration files as well as used for STIGging images.
